# justfile - Task runner for Terraform workflows


# Shell to use
set dotenv-load := true
set fallback := true

quick-apply:
	#!/usr/bin/env bash
	DIR=$(basename $(pwd))
	just quick-apply ${DIR}

quick-destroy:
	#!/usr/bin/env bash
	DIR=$(basename $(pwd))
	just quick-destroy ${DIR}

output:
	#!/usr/bin/env bash
	DIR=$(basename $(pwd))
	just output ${DIR}

get-alb-endpoint:
	#!/usr/bin/env bash
	PROFILE=$(just _aws-profile)
	TF_DIR=$(just _tf-example-dir ecs_app)
	echo "[*]  Get ALB endpoint..."
	cd ${TF_DIR} && AWS_PROFILE=${PROFILE} terraform output -raw nginx_alb_endpoint | xargs echo
